[package]
name = "scene"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
framework = { path = "../framework" }
cgmath="0.18.0"
bytemuck = {version = "1.12.1", features = [ "derive" ] }
